### ISSUE TITLE
Update with Installer 1.2.3 is failing

### ISSUE THREAD

**Issue by claudia-droste-snkeos** [beameio/beame-windows-installer#6]
Gatekeeper service is not stopped by installer.
-> updating Gatekeeper is failing because files cannot be accessed.

**Comment by claudia-droste-snkeos** [comment]
![buginstaller](https://user-images.githubusercontent.com/45553964/50819794-62958b80-132b-11e9-9fc5-2d2db47b66cf.png)

**Comment by organom** [comment]
available with v1.2.4
